<div class="main-container">
    <div class="sidebar">
        <button id="toggle-room-form">+ Ajouter un salon</button>

        <div id="add-room-block" class="hidden-form">
            <form action="index.php?page=room" method="POST">
                <input type="text" id = "addRoom" name="title" required placeholder="Nom du salon">
                <button type="submit" id="btn-save">Enregistrer</button>
            </form>
        </div>

        <ul class="room-list">
            <?php foreach ($rooms as $room): ?>
                <li>
                    <a href="index.php?page=room&id=<?= $room->getId() ?>" 
                       class="<?= (isset($_GET['id']) && $_GET['id'] == $room->getId()) ? 'selected-room' : '' ?>">
                        <?= htmlspecialchars($room->getTitle()) ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <section class="chat-area">
        <?php if ($selectedRoom): ?>
            <?php include "views/chat/chat.phtml"; ?>
        <?php else: ?>
            <p class="welcome-msg">Veuillez sélectionner un salon pour discuter.</p>
        <?php endif; ?>
    </section>
</div>